### ISSUE TITLE
deepin-wine-QQ doesn't work

### ISSUE THREAD

**Issue by PhoenixStarEclipse** [zhtengw/deepin-overlay#45]
When I run `"/opt/deepinwine/apps/Deepin-QQ/run.sh" -u %u`
I get
```
realpath: missing operand
Try 'realpath --help' for more information.
Thu Aug  9 15:21:31 CST 2018:Run Deepin-QQ 8.9.19983deepin22
Thu Aug  9 15:21:31 CST 2018:run Deepin-QQ progress pid 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
total 0
lrwxrwxrwx 1 ag users 10 Aug  9 15:21 c: -> ../drive_c
lrwxrwxrwx 1 ag users 10 Aug  9 14:09 com1 -> /dev/ttyS0
lrwxrwxrwx 1 ag users 10 Aug  9 14:09 com2 -> /dev/ttyS1
lrwxrwxrwx 1 ag users 10 Aug  9 14:09 com3 -> /dev/ttyS2
lrwxrwxrwx 1 ag users 10 Aug  9 14:09 com4 -> /dev/ttyS3
lrwxrwxrwx 1 ag users  8 Aug  9 14:09 lpt1 -> /dev/lp0
lrwxrwxrwx 1 ag users  1 Aug  9 15:21 z: -> /
Thu Aug  9 15:21:31 CST 2018:CallApp Deepin-QQ %u 
Thu Aug  9 15:21:31 CST 2018:kill QQ.exe block
Thu Aug  9 15:21:31 CST 2018:tag bottle: 
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
Thu Aug  9 15:21:31 CST 2018:active bottles: 
Thu Aug  9 15:21:31 CST 2018:start running...
/usr/bin/deepin-wine: line 45: 13732 Segmentation fault      WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"

```

Is it only supposed to run in DDE?

**Comment by zhtengw** [comment]
Yes, I have asked the developer. And the answer was that the windows applications running on deepin-wine support only DDE, other DEs are neglected. See [this thread](https://bbs.deepin.org/forum.php?mod=viewthread&tid=135663&extra=).

**Comment by Lucius3451** [comment]
@zhtengw u mean `deepin-wine-qq` couldn't run on `KDE 5`?
(I couldn't run 'deepin-wine-qq' and `deepin-wine-wechat` on `plasma`)

**Comment by zhtengw** [comment]
@Lucius3451 Yes. 
But I just found someone [does a trick](https://extendswind.top/posts/technical/deepin_wine_run_in_not_gnome_desktop_environment/) to avoid this issue. You can have a try.

**Comment by zhtengw** [comment]
@Lucius3451 , I found [an issue](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12) that discussed further about this. 
1. Emerge gnome-base/gnome-settings-daemon
2. Run /usr/libexec/gsd-xsettings
Then deepin-wine-qq can be run on KDE.

**Comment by Lucius3451** [comment]
@zhtengw thanks for ur reminder

**Comment by Freed-Wu** [comment]
I use gnome 3.32. deepin-wine-QQ cannot work in my computer. the error is similar:

```
19:40:04 wzy@gentoo:~ bash$ /opt/deepinwine/apps/Deepin-QQ/run.sh 
2020年 02月 13日 星期四 19:42:02 CST:Run Deepin-QQ 9.1.8deepin0 c:/Program Files/Tencent/QQ/Bin/QQ.exe
2020年 02月 13日 星期四 19:42:02 CST:run Deepin-QQ progress pid 
总用量 80
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:42 c: -> ../drive_c
lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wzy wzy  8 2月  13 16:05 lpt1 -> /dev/lp0
lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 y: -> /home/wayne
lrwxrwxrwx 1 wzy wzy  1 2月  13 19:42 z: -> /
2020年 02月 13日 星期四 19:42:02 CST:CallApp Deepin-QQ c:/Program Files/Tencent/QQ/Bin/QQ.exe
2020年 02月 13日 星期四 19:42:02 CST:kill QQ.exe block
2020年 02月 13日 星期四 19:42:02 CST:No wine process found
/home/wzy/.deepinwine/Deepin-QQ/drive_c/Program Files/Tencent/QQ/Bin
2020年 02月 13日 星期四 19:42:02 CST:Starting process c:/Program Files/Tencent/QQ/Bin/QQ.exe ...
19:42:02 wzy@gentoo:~ bash$ /usr/bin/deepin-wine: 行 45: 44881 段错误               (核心已转储)WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"
^C
```

I believe gsd-xsetting has run, because

```
19:40:01 wzy@gentoo:~ bash$ /usr/libexec/gsd-xsettings 

(gsd-xsettings:44819): xsettings-plugin-WARNING **: 19:40:04.202: You can only run one xsettings manager at a time; exiting
Failed to start: Could not initialize xsettings manager.
```

i had known there are others encoutering the same error. 

Help!

**Comment by Lucius3451** [comment]
> I use gnome 3.32. deepin-wine-QQ cannot work in my computer. the error is similar:
> 
> ```
> 19:40:04 wzy@gentoo:~ bash$ /opt/deepinwine/apps/Deepin-QQ/run.sh 
> 2020年 02月 13日 星期四 19:42:02 CST:Run Deepin-QQ 9.1.8deepin0 c:/Program Files/Tencent/QQ/Bin/QQ.exe
> 2020年 02月 13日 星期四 19:42:02 CST:run Deepin-QQ progress pid 
> 总用量 80
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:42 c: -> ../drive_c
> lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com1 -> /dev/ttyS0
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com10 -> /dev/ttyS9
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com11 -> /dev/ttyS10
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com12 -> /dev/ttyS11
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com13 -> /dev/ttyS12
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com14 -> /dev/ttyS13
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com15 -> /dev/ttyS14
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 com16 -> /dev/ttyS15
> lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com2 -> /dev/ttyS1
> lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com3 -> /dev/ttyS2
> lrwxrwxrwx 1 wzy wzy 10 2月  13 16:05 com4 -> /dev/ttyS3
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com5 -> /dev/ttyS4
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com6 -> /dev/ttyS5
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com7 -> /dev/ttyS6
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com8 -> /dev/ttyS7
> lrwxrwxrwx 1 wzy wzy 10 2月  13 19:01 com9 -> /dev/ttyS8
> lrwxrwxrwx 1 wzy wzy  8 2月  13 16:05 lpt1 -> /dev/lp0
> lrwxrwxrwx 1 wzy wzy 11 2月  13 19:01 y: -> /home/wayne
> lrwxrwxrwx 1 wzy wzy  1 2月  13 19:42 z: -> /
> 2020年 02月 13日 星期四 19:42:02 CST:CallApp Deepin-QQ c:/Program Files/Tencent/QQ/Bin/QQ.exe
> 2020年 02月 13日 星期四 19:42:02 CST:kill QQ.exe block
> 2020年 02月 13日 星期四 19:42:02 CST:No wine process found
> /home/wzy/.deepinwine/Deepin-QQ/drive_c/Program Files/Tencent/QQ/Bin
> 2020年 02月 13日 星期四 19:42:02 CST:Starting process c:/Program Files/Tencent/QQ/Bin/QQ.exe ...
> 19:42:02 wzy@gentoo:~ bash$ /usr/bin/deepin-wine: 行 45: 44881 段错误               (核心已转储)WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"
> ^C
> ```
> 
> I believe gsd-xsetting has run, because
> 
> ```
> 19:40:01 wzy@gentoo:~ bash$ /usr/libexec/gsd-xsettings 
> 
> (gsd-xsettings:44819): xsettings-plugin-WARNING **: 19:40:04.202: You can only run one xsettings manager at a time; exiting
> Failed to start: Could not initialize xsettings manager.
> ```
> 
> i had known there are others encoutering the same error.
> 
> Help!

看起来像有些东西没装全 google'No wine process found'，应该会有解决方案

**Comment by Freed-Wu** [comment]
试着挑了分辨率，也没有用。。。还在找解决方案QAQ

**Comment by Lucius3451** [comment]
> 试着挑了分辨率，也没有用。。。还在找解决方案QAQ

很多时候出问题 都是缺少必要的包，因此应先保证安装了依赖的包。若error还在的话，再试试重装这系列的包
